xhr = new XMLHttpRequest();
xhr.open("GET","schematic.svg",false);
xhr.overrideMimeType("image/svg+xml");
xhr.send("");
var schematic = document.getElementById("mainWindow").appendChild(xhr.responseXML.documentElement); 


var NONEText = 'Select part from list.';

 var NONEBlackArray = [];
var NONEDarkGrayArray = [];
var NONELightGrayArray = [];
var NONEAquamarineArray = [];
var NONEBlueArray = [];
var NONEPurpleArray = [];
var NONEVioletArray = [];
var NONEPinkArray = [];
var NONEYellowGreenArray = [];
var NONEYellowArray = [];
var NONEOrangeArray = [];
var NONERedArray = [];
var NONEBrownArray = [];

 var bakeElementBlackArray = [path1898,path1902,path2510,path2666,path14083];
var bakeElementDarkGrayArray = [];
var bakeElementLightGrayArray = [];
var bakeElementAquamarineArray = [];
var bakeElementBlueArray = [];
var bakeElementPurpleArray = [];
var bakeElementVioletArray = [];
var bakeElementPinkArray = [];
var bakeElementYellowGreenArray = [];
var bakeElementYellowArray = [];
var bakeElementOrangeArray = [bakeElement];
var bakeElementRedArray = [path54,path1818,path2010,path2154,path2490,path13753,path1286];
var bakeElementBrownArray = [];

 var broilElementBlackArray = [path1902,path2510,path2666,path14083];
var broilElementDarkGrayArray = [];
var broilElementLightGrayArray = [];
var broilElementAquamarineArray = [];
var broilElementBlueArray = [];
var broilElementPurpleArray = [];
var broilElementVioletArray = [];
var broilElementPinkArray = [];
var broilElementYellowGreenArray = [];
var broilElementYellowArray = [];
var broilElementOrangeArray = [broilElement];
var broilElementRedArray = [path1818,path2010,path2482,path2490,path13753];
var broilElementBrownArray = [];

 var latchSwitchBlackArray = [];
var latchSwitchDarkGrayArray = [];
var latchSwitchLightGrayArray = [];
var latchSwitchAquamarineArray = [];
var latchSwitchBlueArray = [];
var latchSwitchPurpleArray = [];
var latchSwitchVioletArray = [];
var latchSwitchPinkArray = [];
var latchSwitchYellowGreenArray = [];
var latchSwitchYellowArray = [];
var latchSwitchOrangeArray = [];
var latchSwitchRedArray = [path38,path46,path870];
var latchSwitchBrownArray = [];

 var ovenSensorBlackArray = [];
var ovenSensorDarkGrayArray = [];
var ovenSensorLightGrayArray = [];
var ovenSensorAquamarineArray = [];
var ovenSensorBlueArray = [];
var ovenSensorPurpleArray = [];
var ovenSensorVioletArray = [];
var ovenSensorPinkArray = [];
var ovenSensorYellowGreenArray = [];
var ovenSensorYellowArray = [];
var ovenSensorOrangeArray = [path518];
var ovenSensorRedArray = [path2582,path2894];
var ovenSensorBrownArray = [];

 var ovenLampBlackArray = [];
var ovenLampDarkGrayArray = [];
var ovenLampLightGrayArray = [];
var ovenLampAquamarineArray = [];
var ovenLampBlueArray = [path954];
var ovenLampPurpleArray = [];
var ovenLampVioletArray = [];
var ovenLampPinkArray = [];
var ovenLampYellowGreenArray = [];
var ovenLampYellowArray = [];
var ovenLampOrangeArray = [ovenLamp];
var ovenLampRedArray = [path2010,path2578,path2662,path13648];
var ovenLampBrownArray = [];

 var burnerLFBlackArray = [lfbPilot,lfbH1,path2846,path3214,path3658,path14368,path4010,path4014,path4202,path4210,path4286,path15478];
var burnerLFDarkGrayArray = [];
var burnerLFLightGrayArray = [];
var burnerLFAquamarineArray = [];
var burnerLFBlueArray = [path15480];
var burnerLFPurpleArray = [];
var burnerLFVioletArray = [];
var burnerLFPinkArray = [];
var burnerLFYellowGreenArray = [];
var burnerLFYellowArray = [];
var burnerLFOrangeArray = [surfaceUnitLIght,path4358];
var burnerLFRedArray = [lfbH2,path3646,path3738,path4042,path4266,path4030,path4242];
var burnerLFBrownArray = [];

 var burnerLRBlackArray = [path1162,path1166,path3094,lrbH1,path3406,lrbPilot,path14779,path3826,path3842,path3854,path3862,path4278,path15478,path14622,path14788];
var burnerLRDarkGrayArray = [];
var burnerLRLightGrayArray = [];
var burnerLRAquamarineArray = [];
var burnerLRBlueArray = [path15480];
var burnerLRPurpleArray = [];
var burnerLRVioletArray = [];
var burnerLRPinkArray = [];
var burnerLRYellowGreenArray = [];
var burnerLRYellowArray = [];
var burnerLROrangeArray = [surfaceUnitLIght,path4354];
var burnerLRRedArray = [lrbH2,path3598,path3638,path3730,path4038,path4262];
var burnerLRBrownArray = [];

 var burnerRFBlackArray = [path2046,rfbPilot,rfbH1,path2938,path3606,path3654,path14614,path3986,path3990,path3998,path4002,path4294,path15478,path14622];
var burnerRFDarkGrayArray = [];
var burnerRFLightGrayArray = [];
var burnerRFAquamarineArray = [];
var burnerRFBlueArray = [path15480];
var burnerRFPurpleArray = [];
var burnerRFVioletArray = [];
var burnerRFPinkArray = [];
var burnerRFYellowGreenArray = [];
var burnerRFYellowArray = [];
var burnerRFOrangeArray = [surfaceUnitLIght,path4362];
var burnerRFRedArray = [rfbH2,path3650,path3734,path4022,path4026,path4046,path4270,path3610];
var burnerRFBrownArray = [];

 var burnerRRBlackArray = [path734,path738,path14850,path3866,path4134,path4146,path4158,rrbH1,rrbPilot,path4258,path4298,path4366,path15478,path14622,path14788];
var burnerRRDarkGrayArray = [];
var burnerRRLightGrayArray = [];
var burnerRRAquamarineArray = [];
var burnerRRBlueArray = [path15480];
var burnerRRPurpleArray = [];
var burnerRRVioletArray = [];
var burnerRRPinkArray = [];
var burnerRRYellowGreenArray = [];
var burnerRRYellowArray = [];
var burnerRROrangeArray = [surfaceUnitLIght,path4338];
var burnerRRRedArray = [path3630,path3726,path3858,rrbH2,path4034,path4114,path4130,path4250];
var burnerRRBrownArray = [];

 var ercACPowerBlackArray = [];
var ercACPowerDarkGrayArray = [];
var ercACPowerLightGrayArray = [];
var ercACPowerAquamarineArray = [];
var ercACPowerBlueArray = [path2446];
var ercACPowerPurpleArray = [];
var ercACPowerVioletArray = [];
var ercACPowerPinkArray = [];
var ercACPowerYellowGreenArray = [];
var ercACPowerYellowArray = [];
var ercACPowerOrangeArray = [path1550];
var ercACPowerRedArray = [path2010,path2538,path13753];
var ercACPowerBrownArray = [];