document.title = "2019 Advantium Oven"
xhr = new XMLHttpRequest();
xhr.open("GET","schematic.svg",false);
xhr.overrideMimeType("image/svg+xml");
xhr.send("");
var schematic = document.getElementById("mainWindow").appendChild(xhr.responseXML.documentElement); 


var NONEText = 'Select part from list.';

// Switches LS1 and LS2 prove maximum and minimum position of the control rod. These switches are located in the control box switch compartment and have a limited range of adjustment. When the two nuts that secure the switches are loosened the switch will pivot on the inner stud and the outer stud can be moved up and down. The switches should be adjusted such that when the collar mounted on the actuator rod is moved into position and pushes in the lever on the switch, the switch will click to the “made” position, but the lever will not bottom out against the switch body. When properly adjusted the lever can move an additional 0.02 inches, as proven by slipping a feeler gauge between the switch lever and the collar when in the “made” position. The collar on the control rod should be adjusted so the switch lever it is actuating will rest squarely on the outer surface of the collar but only 0.03 inches from the edge. If the collar is located for an engagement that is longer than 0.03 inches, the collar may not reach the actuator on the other switch when at the other end of its stroke

var compressorBlackArray = [path3820,path3844,path3896,path3900,path3904,path3908,path3932,path4022,path51987,path52044];
var compressorDarkGrayArray = [];
var compressorLightGrayArray = [];
var compressorAquamarineArray = [];
var compressorBlueArray = [path52055];
var compressorPurpleArray = [];
var compressorVioletArray = [];
var compressorPinkArray = [];
var compressorYellowGreenArray = [];
var compressorYellowArray = [path3920,path3924,path4000,path42844,path52051,path52062];
var compressorOrangeArray = [COMP_path,path6460];
var compressorRedArray = [];
var compressorBrownArray = [];

var outsideFanMotorBlackArray = [path3844,path3896,path3900,path3904,path3908,path3932,path4022,path10364,path10368,path52163,path10328];
var outsideFanMotorDarkGrayArray = [];
var outsideFanMotorLightGrayArray = [];
var outsideFanMotorAquamarineArray = [];
var outsideFanMotorBlueArray = [];
var outsideFanMotorPurpleArray = [];
var outsideFanMotorVioletArray = [];
var outsideFanMotorPinkArray = [];
var outsideFanMotorYellowGreenArray = [];
var outsideFanMotorYellowArray = [path3920,path3924,path4000,path42844,path52062,path52157];
var outsideFanMotorOrangeArray = [path6452,OFM_path];
var outsideFanMotorRedArray = [];
var outsideFanMotorBrownArray = [path52160];

var indoorFanMotorBlackArray = [path52296,path52298];
var indoorFanMotorDarkGrayArray = [];
var indoorFanMotorLightGrayArray = [];
var indoorFanMotorAquamarineArray = [];
var indoorFanMotorBlueArray = [];
var indoorFanMotorPurpleArray = [];
var indoorFanMotorVioletArray = [];
var indoorFanMotorPinkArray = [];
var indoorFanMotorYellowGreenArray = [];
var indoorFanMotorYellowArray = [path4086,path52168];
var indoorFanMotorOrangeArray = [IFM_path];
var indoorFanMotorRedArray = [];
var indoorFanMotorBrownArray = [path52285,path52406];

var contactorCoilBlackArray = [];
var contactorCoilDarkGrayArray = [];
var contactorCoilLightGrayArray = [];
var contactorCoilAquamarineArray = [];
var contactorCoilBlueArray = [path10942];
var contactorCoilPurpleArray = [];
var contactorCoilVioletArray = [];
var contactorCoilPinkArray = [];
var contactorCoilYellowGreenArray = [];
var contactorCoilYellowArray = [];
var contactorCoilOrangeArray = [C1C2_path];
var contactorCoilRedArray = [];
var contactorCoilBrownArray = [path52497];

var crankCaseHeaterBlackArray = [path52078,path52441];
var crankCaseHeaterDarkGrayArray = [];
var crankCaseHeaterLightGrayArray = [];
var crankCaseHeaterAquamarineArray = [];
var crankCaseHeaterBlueArray = [];
var crankCaseHeaterPurpleArray = [];
var crankCaseHeaterVioletArray = [];
var crankCaseHeaterPinkArray = [];
var crankCaseHeaterYellowGreenArray = [];
var crankCaseHeaterYellowArray = [];
var crankCaseHeaterOrangeArray = [];
var crankCaseHeaterRedArray = [];
var crankCaseHeaterBrownArray = [];

var defrostBoardBlackArray = [path52078,path52441];
var defrostBoardDarkGrayArray = [];
var defrostBoardLightGrayArray = [];
var defrostBoardAquamarineArray = [];
var defrostBoardBlueArray = [];
var defrostBoardPurpleArray = [];
var defrostBoardVioletArray = [];
var defrostBoardPinkArray = [];
var defrostBoardYellowGreenArray = [];
var defrostBoardYellowArray = [];
var defrostBoardOrangeArray = [];
var defrostBoardRedArray = [defrostBoard];
var defrostBoardBrownArray = [];

var defrostThermostatBlackArray = [];
var defrostThermostatDarkGrayArray = [];
var defrostThermostatLightGrayArray = [];
var defrostThermostatAquamarineArray = [];
var defrostThermostatBlueArray = [];
var defrostThermostatPurpleArray = [];
var defrostThermostatVioletArray = [];
var defrostThermostatPinkArray = [path52457,path52468];
var defrostThermostatYellowGreenArray = [];
var defrostThermostatYellowArray = [];
var defrostThermostatOrangeArray = [path11004,path11032];
var defrostThermostatRedArray = [];
var defrostThermostatBrownArray = [];

var highPressureSwitchBlackArray = [path11640,path56541];
var highPressureSwitchDarkGrayArray = [];
var highPressureSwitchLightGrayArray = [];
var highPressureSwitchAquamarineArray = [];
var highPressureSwitchBlueArray = [path11090,path11170];
var highPressureSwitchPurpleArray = [];
var highPressureSwitchVioletArray = [];
var highPressureSwitchPinkArray = [];
var highPressureSwitchYellowGreenArray = [];
var highPressureSwitchYellowArray = [];
var highPressureSwitchOrangeArray = [path11194,path2811,path2809,path2807,HPS_path];
var highPressureSwitchRedArray = [];
var highPressureSwitchBrownArray = [];

 var inducedDraftMotorBlackArray = [];
var inducedDraftMotorDarkGrayArray = [];
var inducedDraftMotorLightGrayArray = [];
var inducedDraftMotorAquamarineArray = [];
var inducedDraftMotorBlueArray = [];
var inducedDraftMotorPurpleArray = [];
var inducedDraftMotorVioletArray = [path52122,path52342];
var inducedDraftMotorPinkArray = [];
var inducedDraftMotorYellowGreenArray = [];
var inducedDraftMotorYellowArray = [path52116,path52118,path52345];
var inducedDraftMotorOrangeArray = [CAP2_path,IDM_path];
var inducedDraftMotorRedArray = [path52131,path52333,path52339];
var inducedDraftMotorBrownArray = [path9914,path9918];

 var integratedGasControllerBlackArray = [];
var integratedGasControllerDarkGrayArray = [];
var integratedGasControllerLightGrayArray = [];
var integratedGasControllerAquamarineArray = [];
var integratedGasControllerBlueArray = [];
var integratedGasControllerPurpleArray = [];
var integratedGasControllerVioletArray = [];
var integratedGasControllerPinkArray = [];
var integratedGasControllerYellowGreenArray = [];
var integratedGasControllerYellowArray = [];
var integratedGasControllerOrangeArray = [];
var integratedGasControllerRedArray = [integratedGasControllerBorder];
var integratedGasControllerBrownArray = [];

var limitSwitch1BlackArray = [];
var limitSwitch1DarkGrayArray = [];
var limitSwitch1LightGrayArray = [];
var limitSwitch1AquamarineArray = [];
var limitSwitch1BlueArray = [];
var limitSwitch1PurpleArray = [];
var limitSwitch1VioletArray = [path3412,path5336,path8904];
var limitSwitch1PinkArray = [];
var limitSwitch1YellowGreenArray = [];
var limitSwitch1YellowArray = [];
var limitSwitch1OrangeArray = [path5260,path5264,path5268,path5272,path5276];
var limitSwitch1RedArray = [path52445];
var limitSwitch1BrownArray = [];

var limitSwitch2BlackArray = [];
var limitSwitch2DarkGrayArray = [];
var limitSwitch2LightGrayArray = [];
var limitSwitch2AquamarineArray = [];
var limitSwitch2BlueArray = [];
var limitSwitch2PurpleArray = [];
var limitSwitch2VioletArray = [path3412,path5336,path8904];
var limitSwitch2PinkArray = [];
var limitSwitch2YellowGreenArray = [];
var limitSwitch2YellowArray = [];
var limitSwitch2OrangeArray = [path5292,path5296,path5300,path5304,path5308];
var limitSwitch2RedArray = [path52445];
var limitSwitch2BrownArray = [];

var lowGasPressureSensorBlackArray = [];
var lowGasPressureSensorDarkGrayArray = [];
var lowGasPressureSensorLightGrayArray = [];
var lowGasPressureSensorAquamarineArray = [];
var lowGasPressureSensorBlueArray = [];
var lowGasPressureSensorPurpleArray = [];
var lowGasPressureSensorVioletArray = [];
var lowGasPressureSensorPinkArray = [];
var lowGasPressureSensorYellowGreenArray = [];
var lowGasPressureSensorYellowArray = [path5620,path5628,path52430,path52433];
var lowGasPressureSensorOrangeArray = [path5624,path5632,path5742,path52438];
var lowGasPressureSensorRedArray = [];
var lowGasPressureSensorBrownArray = [];

var lowPressureSwitchBlackArray = [path11194,path11640,path56541];
var lowPressureSwitchDarkGrayArray = [];
var lowPressureSwitchLightGrayArray = [];
var lowPressureSwitchAquamarineArray = [];
var lowPressureSwitchBlueArray = [path11090,path11170];
var lowPressureSwitchPurpleArray = [];
var lowPressureSwitchVioletArray = [];
var lowPressureSwitchPinkArray = [];
var lowPressureSwitchYellowGreenArray = [];
var lowPressureSwitchYellowArray = [];
var lowPressureSwitchOrangeArray = [path11094,LPS_path,path2819,path2817,path11148];
var lowPressureSwitchRedArray = [];
var lowPressureSwitchBrownArray = [];

var mainGasValveBlackArray = [];
var mainGasValveDarkGrayArray = [path52421];
var mainGasValveLightGrayArray = [];
var mainGasValveAquamarineArray = [];
var mainGasValveBlueArray = [path52427];
var mainGasValvePurpleArray = [];
var mainGasValveVioletArray = [];
var mainGasValvePinkArray = [];
var mainGasValveYellowGreenArray = [];
var mainGasValveYellowArray = [];
var mainGasValveOrangeArray = [MGV_path];
var mainGasValveRedArray = [];
var mainGasValveBrownArray = [path8900];

var pressureSwitchBlackArray = [];
var pressureSwitchDarkGrayArray = [];
var pressureSwitchLightGrayArray = [];
var pressureSwitchAquamarineArray = [];
var pressureSwitchBlueArray = [];
var pressureSwitchPurpleArray = [];
var pressureSwitchVioletArray = [];
var pressureSwitchPinkArray = [];
var pressureSwitchYellowGreenArray = [];
var pressureSwitchYellowArray = [path5620,path5628,path52430,path52433];
var pressureSwitchOrangeArray = [path5538,path5542,path5546,path5550,path5554,path5558,path5562,path5624,path5632,path5742,path52438];
var pressureSwitchRedArray = [];
var pressureSwitchBrownArray = [];

var reversingValveSolenoidBlackArray = [path52525];
var reversingValveSolenoidDarkGrayArray = [];
var reversingValveSolenoidLightGrayArray = [];
var reversingValveSolenoidAquamarineArray = [];
var reversingValveSolenoidBlueArray = [];
var reversingValveSolenoidPurpleArray = [];
var reversingValveSolenoidVioletArray = [];
var reversingValveSolenoidPinkArray = [];
var reversingValveSolenoidYellowGreenArray = [];
var reversingValveSolenoidYellowArray = [];
var reversingValveSolenoidOrangeArray = [RVS_path];
var reversingValveSolenoidRedArray = [];
var reversingValveSolenoidBrownArray = [path52522];

var rollOverSwitchBlackArray = [];
var rollOverSwitchDarkGrayArray = [];
var rollOverSwitchLightGrayArray = [];
var rollOverSwitchAquamarineArray = [];
var rollOverSwitchBlueArray = [path744,path748,path5252,path5256,path6936];
var rollOverSwitchPurpleArray = [];
var rollOverSwitchVioletArray = [];
var rollOverSwitchPinkArray = [];
var rollOverSwitchYellowGreenArray = [];
var rollOverSwitchYellowArray = [];
var rollOverSwitchOrangeArray = [path5340,path5344,path5348,path5352,path5356];
var rollOverSwitchRedArray = [];
var rollOverSwitchBrownArray = [];

var transformerBlackArray = [path3932,path4022,path51987,path52070,path52378];
var transformerDarkGrayArray = [];
var transformerLightGrayArray = [];
var transformerAquamarineArray = [];
var transformerBlueArray = [];
var transformerPurpleArray = [];
var transformerVioletArray = [];
var transformerPinkArray = [];
var transformerYellowGreenArray = [];
var transformerYellowArray = [path4000,path42844,path52058,path52062,path52097];
var transformerOrangeArray = [path4354,TRAN_path];
var transformerRedArray = [path52412];
var transformerBrownArray = [path3657];

